---
  - name: Probe default ssh port
    command: /bin/true
    ignore_unreachable: yes
    register: port_check_result
  - name: Set custom ansible_port if required 
    set_fact:
      ansible_port: "{{ custom_ssh_port }}"
    when: port_check_result.msg is defined and port_banned_substring in port_check_result.msg
  - name: Disable Root SSH Login
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: "PermitRootLogin no"
      state: present
      backup: yes
    notify:
       - restart ssh
  - name: Setup custom SSH port
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^Port 22'
      line: "Port {{ansible_port}}"
      insertbefore: BOF
      backup: yes
    notify:
       - restart ssh
  - name: Ban common SSH port
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^Port 22'
      state: absent
      backup: yes
    notify:
       - restart ssh
  - name: Reboot VM
    reboot:
