---
- name: Ban root ssh login
  hosts: production
  tasks:
  - name: Disable Root SSH Login
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: "PermitRootLogin no"
      state: present
      backup: yes
    notify:
       - restart ssh #todo: frequent error ERROR! The requested handler 'restart ssh' was not found in either the main handlers list nor in the listening handlers list
    become: true
  - name: Reboot VM
    reboot:
    become: true
